using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Drawing;
using System.Drawing.Imaging;

namespace ChordnomiconWebApplication.Images
{
    public static class RandomColorFactory
    {
        static List<Brush> brushes = new List<Brush>()
        {
            Brushes.AliceBlue,
            Brushes.Aqua,
            Brushes.Aquamarine,
            Brushes.Azure,
            Brushes.Bisque,
            Brushes.Blue,
            Brushes.BlueViolet,
            Brushes.BurlyWood,
            Brushes.CadetBlue,
            Brushes.Chartreuse,
            Brushes.Chocolate,
            Brushes.Coral,
            Brushes.CornflowerBlue,
            Brushes.Cornsilk,
            Brushes.Crimson,
            Brushes.Cyan,
            Brushes.DarkBlue,
            Brushes.DarkCyan,
            Brushes.DarkGoldenrod,
            Brushes.DarkGreen,
            Brushes.DarkMagenta,
            Brushes.DarkOliveGreen,
            Brushes.DarkOrange,
            Brushes.DarkOrchid,
            Brushes.DarkRed,
            Brushes.DarkSalmon,
            Brushes.DarkSeaGreen,
            Brushes.DarkSlateBlue,
            Brushes.DarkTurquoise,
            Brushes.DarkViolet,
            Brushes.DeepPink,
            Brushes.DeepSkyBlue,
            Brushes.DodgerBlue,
            Brushes.Firebrick,
            Brushes.ForestGreen,
            Brushes.Fuchsia,
            Brushes.Gainsboro,
            Brushes.Gold,
            Brushes.Goldenrod,
            Brushes.Green,
            Brushes.GreenYellow,
            Brushes.Honeydew,
            Brushes.HotPink,
            Brushes.IndianRed,
            Brushes.Indigo,
            Brushes.Lavender,
            Brushes.LavenderBlush,
            Brushes.LawnGreen,
            Brushes.LemonChiffon,
            Brushes.LightBlue,
            Brushes.LightCoral,
            Brushes.LightCyan,
            Brushes.LightGreen,
            Brushes.LightSeaGreen,
            Brushes.LightSkyBlue,
            Brushes.LightSteelBlue,
            Brushes.Lime,
            Brushes.LimeGreen,
            Brushes.Linen,
            Brushes.Magenta,
            Brushes.Maroon,
            Brushes.MediumAquamarine,
            Brushes.MediumBlue,
            Brushes.MediumOrchid,
            Brushes.MediumPurple,
            Brushes.MediumSeaGreen,
            Brushes.MediumSlateBlue,
            Brushes.MediumSpringGreen,
            Brushes.MediumTurquoise,
            Brushes.MediumVioletRed,
            Brushes.MidnightBlue,
            Brushes.MintCream,
            Brushes.MistyRose,
            Brushes.Navy,
            Brushes.OldLace,
            Brushes.Olive,
            Brushes.OliveDrab,
            Brushes.Orange,
            Brushes.OrangeRed,
            Brushes.Orchid,
            Brushes.PaleGoldenrod,
            Brushes.PaleGreen,
            Brushes.PaleTurquoise,
            Brushes.PaleVioletRed,
            Brushes.PapayaWhip,
            Brushes.PeachPuff,
            Brushes.Peru,
            Brushes.Pink,
            Brushes.Plum,
            Brushes.PowderBlue,
            Brushes.Purple,
            Brushes.Red,
            Brushes.RosyBrown,
            Brushes.RoyalBlue,
            Brushes.SaddleBrown,
            Brushes.Salmon,
            Brushes.SandyBrown,
            Brushes.SeaGreen,
            Brushes.SeaShell,
            Brushes.Sienna,
            Brushes.Silver,
            Brushes.SkyBlue,
            Brushes.SlateBlue,
            Brushes.SpringGreen,
            Brushes.SteelBlue,
            Brushes.Teal,
            Brushes.Thistle,
            Brushes.Tomato,
            Brushes.Turquoise,
            Brushes.Violet,
            Brushes.Wheat,
            Brushes.Yellow,
            Brushes.YellowGreen
        };
        public static Brush GetRandomColor()
        {
            Random random = new Random();
            int seed = random.Next(brushes.Count() - 1);
            Brush tempBrush = brushes.ElementAt(seed);
            return tempBrush;
        }
    }
}